-- AlterTable
ALTER TABLE "game" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "homeTeamScore" SET DEFAULT 0,
ALTER COLUMN "awayTeamScore" SET DEFAULT 0,
ALTER COLUMN "isFinished" SET DEFAULT false;
